{
    "__common__": "",
    "CuckooPort": "Cuckoo port",
    "GatewayPort": "Gateway port",
    "SwarmPort": "Cluster port",
    "Subscribe": "Subscribe",
    "UnSubscribe": "Unsubscribe",
    "VideoList": "Playlist",
    "Modify": "Edit",
    "Video": "Video",
    "Playlists": "Playlists",
    "Devices": "Devices",
    "Settings": "Settings",
    "DeleteOrNot": "Confirm deletion of file?",
    "DeleteConfirm": "Confirm",
    "DeleteCancel": "Cancel",
    "Add": "Add to",
    "Edit": "Edit",
    "ChannelCategory": "Category",
    "ChannelTitle": "Channel",
    "ChannelDescription": "Channel Description",
    "Save": "Save",
    "SharingCode": "Sharing Code",
    "Collection": "Collection",
    "CommentContentPlaceholder": "Add a public comment",
    "CommentContentPlaceholderError": "It can not be commented when user is offline",
    "Comment": "Comment",
    "Reply": "Reply",
    "Category1": "Pets & Animals",
    "Category2": "Films & Cartoons",
    "Category3": "Public & social activities",
    "Category4": "Education",
    "Category5": "Science & Tech",
    "Category6": "Tourism & Activities",
    "Category7": "Automatic",
    "Category8": "People & Blogs",
    "Category9": "Sports",
    "Category10": "Comedy",
    "Category11": "News & Politics",
    "Category12": "Music",
    "Category13": "Gaming",
    "Category14": "Entertainment",
    "Category15": "DIY & Life",
    "Category16": "TV Shows",
    "Category100": "Adult Videos",
    "SensitiveContent": "This media may contain sensitive material",
    "View": "View",
    "MySubscribe": "My subscription",
    "HotVideo": "Popular Videos",
    "RecommendVideo": "Recommended Videos",
    "HotChannel": "Popular channels",
    "RecommendChannel": "Recommended channels",
    "Loading": "Cuckoo is loading, please wait for a while",
    "Quit": "Quit",

    "__install__": "",
    "InstallTitle": "Install Cuckoo",
    "InstallDirectory": "Installation directory",
    "InstallSelect": "Select",
    "InstallLang": "Language",
    "Install": "Install",
    "InstallRecovery": "Recovery",

    "__nav__": "",
    "PreviousPage": "Previous Page",
    "NextPage": "Next Page",
    "Main": "Home",
    "Channels": "Channel",
    "Refresh": "Refresh",
    "Code": "Search or Enter sharing code",
    "BtnCode": "Browse",
    "Upload": "Uploading",
    "Download": "Download",
    "My": "My channel",

    "__footer__": "",
    "P2Pconnections": "Connections",
    "Preloading": "Preloading",
    "NoPreloadingTask": "No preloading task",
    "SystemSettings": "System Settings",
    "P2PState": "Space Used",
    "About": "About",

    "__index__": "",
    "IndexMyEmpty": "No video, for more videos please check ~HotVideo~ or ~RecommendVideo~",

    "__channels__": "",
    "ChannelsMyEmpty": "No subscribed channel, for more channels please check ~HotChannel~ or ~RecommendChannel~",

    "__my__": "",
    "MyVideoEmpty": "If you have not posted any video, please ~Upload~ a video to share with your family and friends",
    "MyPlaylistEmpty": "No playlist, please click the ~+~ button to create",
    "PlaylistTitle": "Playlist title",
    "PlaylistTitleError": "Repeat playlist title",
    "PlaylistThumbnail": "Playlist thumbnail",
    "PlaylistDescription": "Playlist description",
    "ClientManufacturer": "Manufacturer",
    "ClientBrand": "Brand",
    "ClientIP": "IP",
    "ClientUniqueID": "ID",
    "ChannelTitleError": "Please enter your Channel name",
    "SuccessfullySetup": "Setting successfully",
    "SetupFailed": "Setting failed",

    "__player__": "",
    "VideoCancel": "Cancel",
    "VideoReplay": "Replay",
    "VideoPassword": "Video password",
    "VideoDecrypt": "Decryption",
    "SetSubtitle": "Set subtitle",
    "CurrentSubtitle": "Current subtitle",
    "SubtitleDelay": "Subtitle delay",
    "SubtitleSize": "Subtitle size",
    "SubtitlePosition": "Subtitle position",
    "SubtitleBackground": "Subtitle background",
    "FloatOnTop": "Float on top",

    "VideoCannotPlay": "This video can not be played",
    "SuccessfulCollection": "Collecting successfully",
    "AlreadyCollection": "Favorite",
    "FailedCollection": "Collecting failed",
    "SendCommentMsg": "Your comments are being reviewed",
    "SendCommentMsgFailed": "Please comment after a 30-second interval",
    "SkipAd": "Skip ads",
    "PasswordError": "Wrong password",

    "__settings__": "",
    "FilePath": "File",
    "DownloadPath": "Download path",
    "PathSelect": "Select",
    "FileSpace": "Space",
    "FileSpacePlaceholder": "Setting Space",
    "Lang": "Language",
    "BackUp": "Back-up",
    "Theme": "Theme",

    "FileSpaceFailedSave": "The space needs to be more than 10GB",
    "SuccessfullySaved": "Saving Successfully",
    "SuccessfullyBackUp": "Back-up successfully",
    "FailedBackUp": "Back-up failed",

    "__upload__": "",
    "UploadCardTitle": "Select the file to upload",
    "UploadCardText": "Drag the video file here",
    "UploadThumbnail": "Video Thumbnail",
    "UploadMakeThumbnail": "Screen Thumbnail",
    "UploadCategory": "Category",
    "UploadTitle": "Title",
    "UploadDescription": "Description",
    "UploadSubtitles": "Set subtitles",
    "UploadPassword": "Set password",
    "UploadRepassword": "Confirm password",
    "UploadRelease": "Release",

    "PleaseCreateChannel": "Please create a channel",
    "UploadTypeError": "This format is not supported",
    "UploadSubtitlesFile": "Subtitle file",
    "UploadSubtitlesLabel": "Subtitle label",
    "UploadThumbnailError": "The thumbnail can not be empty",
    "UploadTitleError": "The title can not be empty",
    "UploadSubtitlesLabelError": "Subtitle label cannot be empty",
    "UploadPasswordError": "Two passwords are different",
    "SuccessfulRelease": "Releasing successfully",
    "FailedRelease": "Releasing failed",

    "__download__": "",
    "DownloadList": "Download list",
    "DownloadPlaceholder": "Magnet link",
    "Downloaded": "Downloaded",
    "DownloadRemaining": "Remaining",
    "DownloadPaused": "Paused",

    "__edit__": "",
    "EditPasswordPlaceholder": "The password will not be changed if it is empty",
    "EditTip": "Available Edits",
    "SuccessfulEdit": "Edit successfully",
    "FailedEdit": "Edit unsuccessfully",

    "__search__": "",
    "SearchResults": "Search results",

    "__menu__": "",
    "Undo": "Undo",
    "Redo": "Redo",
    "Cut": "Cut",
    "Copy": "Copy",
    "Paste": "Paste",
    "SelectAll": "Select All"
}
