{
    "__common__": "",
    "Subscribe": "Subscribe",
    "UnSubscribe": "Unsubscribe",
    "VideoList": "Playlist",
    "Modify": "Edit",
    "Video": "Video",
    "Settings": "Settings",
    "ChannelCategory": "Category",
    "ChannelTitle": "Channel",
    "ChannelDescription": "Channel Description",
    "Save": "Save",
    "Collection": "Collection",
    "CommentContentPlaceholder": "Add a public comment",
    "Comment": "Comment",
    "Reply": "Reply",
    "Category1": "Pets & Animals",
    "Category2": "Films & Cartoons",
    "Category3": "Public & social activities",
    "Category4": "Education",
    "Category5": "Science & Tech",
    "Category6": "Tourism & Activities",
    "Category7": "Automatic",
    "Category8": "People & Blogs",
    "Category9": "Sports",
    "Category10": "Comedy",
    "Category11": "News & Politics",
    "Category12": "Music",
    "Category13": "Gaming",
    "Category14": "Entertainment",
    "Category15": "DIY & Life",
    "Loading": "Cuckoo Loading, please wait for momentload……",

    "__nav__": "",
    "PreviousPage": "Previous Page",
    "NextPage": "Next Page",
    "Main": "Home",
    "Channels": "Channel",
    "Refresh": "Refresh",
    "Code": "Sharing Code",
    "BtnCode": "Browse",
    "Upload": "Uploading",
    "My": "My channel",

    "__footer__": "",
    "P2Pconnections": "Connections",
    "SystemSettings": "System Settings",
    "P2PState": "Space Used",
    "About": "About",

    "__my__": "",
    "ChannelTitleError": "Please enter your Channel name",
    "SuccessfullySetup": "Setting successfully",
    "SetupFailed": "Setting failed",

    "__player__": "",
    "SuccessfulCollection": "Collecting successfully",
    "AlreadyCollection": "Favorite",
    "FailedCollection": "Collecting failed",
    "SendCommentMsg": "Your comments are being reviewed",
    "SendCommentMsgFailed": "Comment failed with interval greater than 30 seconds",
    "SkipAd": "Skip ads",

    "__settings__": "",
    "FilePath": "File",
    "FileSpace": "Space",
    "FileSpacePlaceholder": "Setting Space",
    "Lang": "Language",
    "BackUp": "Back-up",

    "FileSpaceFailedSave": "The space needs to be more than 10GB",
    "SuccessfullySaved": "Saving Successfully",
    "SuccessfullyBackUp": "Back-up successfully",
    "FailedBackUp": "Back-up failed",

    "__upload__": "",
    "UploadCardTitle": "Select the file to upload",
    "UploadCardText": "Drag the video file here",
    "UploadThumbnail": "Video Thumbnail",
    "UploadMakeThumbnail": "Screen Thumbnail",
    "UploadCategory": "Category",
    "UploadTitle": "Title",
    "UploadDescription": "Description",
    "UploadRelease": "Release",

    "PleaseCreateChannel": "Please create a channel",
    "UploadTypeError": "Format does not support",
    "UploadThumbnailError": "The thumbnail can not be empty",
    "UploadTitleError": "The title can not be empty",
    "SuccessfulRelease": "Releasing successfully",
    "FailedRelease": "Releasing failed",

    "__menu__": "",
    "Undo": "Undo",
    "Redo": "Redo",
    "Cut": "Cut",
    "Copy": "Copy",
    "Paste": "Paste",
    "SelectAll": "Select All"
}
