{
    "__common__": "",
    "CuckooPort": "Cuckoo port",
    "GatewayPort": "Port de passerelle",
    "SwarmPort": "Port de cluster",
    "Subscribe": "Souscrire",
    "UnSubscribe": "Se désabonner",
    "VideoList": "Playlist",
    "Modify": "modifier",
    "Video": "Vidéo",
    "Settings": "Paramètres",
    "DeleteOrNot": "Confirmer la suppression?",
    "DeleteConfirm": "Confirmer",
    "DeleteCancel": "Annuler",
    "ChannelCategory": "Catégorie",
    "ChannelTitle": "Canal",
    "ChannelDescription": "Description de la chaîne",
    "Save": "sauvegarder",
    "Collection": "Collection",
    "CommentContentPlaceholder": "Ajouter un commentaire public",
    "CommentContentPlaceholderError": "Il ne peut pas être commenté lorsque l'utilisateur est déconnecté",
    "Comment": "Ajouter un commentaire",
    "Reply": "Répondre",
    "Category1": "Animaux",
    "Category2": "Films & Animation",
    "Category3": "Activités publiques et sociales",
    "Category4": "Éducation",
    "Category5": "Science et technologie",
    "Category6": "Tourisme et activités",
    "Category7": "Vehicule",
    "Category8": "People & blogs",
    "Category9": "Sports",
    "Category10": "Comédie",
    "Category11": "Informations & politique",
    "Category12": "Musique",
    "Category13": "Jeux video",
    "Category14": "Divertissement",
    "Category15": "DIY & vie",
    "Category16": "émission de télévision",
    "Category100": "Vidéos Adulte",
    "SensitiveContent": "Cette vidéo peut contenir des informations sensibles",
    "View": "Voir",
    "MySubscribe": "Mon abonnement",
    "HotVideo": "Vidéo populaire",
    "RecommendVideo": "Vidéo recommandée",
    "HotChannel": "Chaîne populaire",
    "RecommendChannel": "Chaîne recommandée",
    "Loading": "Cuckoo se charge, s'il vous plaît attendez un moment",
    "Quit": "Fermer",

    "__install__": "",
    "InstallTitle": "Installer Cuckoo",
    "InstallDirectory": "Répertoire d'installation",
    "InstallSelect": "Choisissez",
    "InstallLang": "Langue",
    "Install": "Installation",
    "InstallRecovery": "Récupération",

    "__nav__": "",
    "PreviousPage": "Page précédente",
    "NextPage": "Page suivante",
    "Main": "Accueil",
    "Channels": "Canal",
    "Refresh": "Rafraîchir",
    "Code": "Code de partage",
    "BtnCode": "Afficher",
    "Upload": "Téléchargement",
    "My": "Ma Chaîne",

    "__footer__": "",
    "P2Pconnections": "Les liaisons",
    "Preloading": "Préchargement",
    "NoPreloadingTask": "Aucune tâche préchargement",
    "SystemSettings": "Les paramètres du système",
    "P2PState": "Espace ocupe",
    "About": "À propos",

    "__my__": "",
    "ChannelTitleError": "Veuillez entrer le nom de la chaîne",
    "SuccessfullySetup": "Réglage avec succès",
    "SetupFailed": "Échec",

    "__player__": "",
    "VideoCancel": "Annuler",
    "VideoReplay": "Rejouer",
    "VideoPassword": "Mot de passe vidéo",
    "VideoDecrypt": "Décrypter",
    "SetSubtitle": "Définir les sous-titres",
    "CurrentSubtitle": "Sous-titre actuel",
    "SubtitleDelay": "Délai de sous-titre",
    "SubtitleSize": "Taille des sous-titres",
    "SubtitlePosition": "Position des sous-titres",

    "VideoCannotPlay": "Cette vidéo ne peut être joué",
    "SuccessfulCollection": "Collection avec succès",
    "AlreadyCollection": "Favoris",
    "FailedCollection": "Collection en échec",
    "SendCommentMsg": "Vos commentaires sont en cours de révision",
    "SendCommentMsgFailed": "S'il vous plaît commenter après un intervalle de 30 secondes",
    "SkipAd": "Sauter les annonces",
    "PasswordError": "Mot de passe incorrect",

    "__settings__": "",
    "FilePath": "Fichier",
    "FileSpace": "Espace",
    "FileSpacePlaceholder": "Espace de réglage",
    "Lang": "Langue",
    "BackUp": "Sauvegarde",

    "FileSpaceFailedSave": "L'espace doit être supérieur à 10 Go",
    "SuccessfullySaved": "Enregistrement avec succès",
    "SuccessfullyBackUp": "Sauvegarde avec succès",
    "FailedBackUp": "Sauvegarde en échec",

    "__upload__": "",
    "UploadCardTitle": "Sélectionner le fichier à télécharger",
    "UploadCardText": "Glisser le fichier vidéo ici",
    "UploadThumbnail": "Vignette de vidéo",
    "UploadMakeThumbnail": "Vignette d'écran",
    "UploadCategory": "Catégorie",
    "UploadTitle": "Titre",
    "UploadDescription": "La description",
    "UploadPassword": "Définir le mot",
    "UploadRepassword": "Confirmer le mot",
    "UploadRelease": "Publier",

    "PleaseCreateChannel": "Créer une chaîne",
    "UploadTypeError": "Ce format n'est pas supporté",
    "UploadThumbnailError": "Veuillez montrer la vignette de la vidéo",
    "UploadTitleError": "S'il vous plaît entrez le titre",
    "UploadPasswordError": "Deux mots de passe sont différents",
    "SuccessfulRelease": "Publication avec succès",
    "FailedRelease": "Publication en échec",

    "__edit__": "",
    "EditPasswordPlaceholder": "Le mot de passe ne sera pas changé s'il est vide",
    "Edit": "Modifier",
    "EditTip": "Modifications disponibles",
    "SuccessfulEdit": "éditer avec succès",
    "FailedEdit": "modifier sans succès",

    "__menu__": "",
    "Undo": "Annuler",
    "Redo": "Refaire",
    "Cut": "Écrêtage",
    "Copy": "Copier",
    "Paste": "Coller",
    "SelectAll": "Sélectionner tout"
}
