{
    "__common__": "",
    "Subscribe": "Souscrire",
    "UnSubscribe": "Se désabonner",
    "VideoList": "Playlist",
    "Modify": "modifier",
    "Video": "Vidéo",
    "Settings": "Paramètres",
    "ChannelCategory": "Catégorie",
    "ChannelTitle": "Canal",
    "ChannelDescription": "Description de la chaîne",
    "Save": "sauvegarder",
    "Collection": "Collection",
    "CommentContentPlaceholder": "Ajouter un commentaire public",
    "Comment": "Ajouter un commentaire",
    "Reply": "Répondre",
    "Category1": "Animaux",
    "Category2": "Films & Animation",
    "Category3": "Activités publiques et sociales",
    "Category4": "Éducation",
    "Category5": "Science et technologie",
    "Category6": "Tourisme et activités",
    "Category7": "Vehicule",
    "Category8": "People & blogs",
    "Category9": "Sports",
    "Category10": "Comédie",
    "Category11": "Informations & politique",
    "Category12": "Musique",
    "Category13": "Jeux video",
    "Category14": "Divertissement",
    "Category15": "DIY & vie",
    "Category100": "Vidéos pour adultes",
    "SensitiveContent": "Ce support peut contenir du contenu sensible",
    "View": "Voir",
    "Loading": "Cuckoo est en train de charger",

    "__nav__": "",
    "PreviousPage": "Page précédente",
    "NextPage": "Page suivante",
    "Main": "Accueil",
    "Channels": "Canal",
    "Refresh": "Rafraîchir",
    "Code": "Code de partage",
    "BtnCode": "Afficher",
    "Upload": "Téléchargement",
    "My": "Ma Chaîne",

    "__footer__": "",
    "P2Pconnections": "Les liaisons",
    "SystemSettings": "Les paramètres du système",
    "P2PState": "Espace ocupe",
    "About": "À propos",

    "__my__": "",
    "ChannelTitleError": "Veuillez entrer le nom de la chaîne",
    "SuccessfullySetup": "Réglage avec succès",
    "SetupFailed": "Échec",

    "__player__": "",
    "VideoCancel": "Annulation",
    "VideoReplay": "Rejouer",

    "SuccessfulCollection": "Collection avec succès",
    "AlreadyCollection": "Favoris",
    "FailedCollection": "Collection en échec",
    "SendCommentMsg": "Vos commentaires sont en cours de révision",
    "SendCommentMsgFailed": "Le commentaire a échoué avec un intervalle supérieur à 30 secondes",
    "SkipAd": "Sauter les annonces",

    "__settings__": "",
    "FilePath": "Fichier",
    "FileSpace": "Espace",
    "FileSpacePlaceholder": "Espace de réglage",
    "Lang": "Langue",
    "BackUp": "Sauvegarde",

    "FileSpaceFailedSave": "L'espace doit être supérieur à 10 Go",
    "SuccessfullySaved": "Enregistrement avec succès",
    "SuccessfullyBackUp": "Sauvegarde avec succès",
    "FailedBackUp": "Sauvegarde en échec",

    "__upload__": "",
    "UploadCardTitle": "Sélectionner le fichier à télécharger",
    "UploadCardText": "Glisser le fichier vidéo ici",
    "UploadThumbnail": "Vignette de vidéo",
    "UploadMakeThumbnail": "Vignette d'écran",
    "UploadCategory": "Catégorie",
    "UploadTitle": "Titre",
    "UploadDescription": "La description",
    "UploadRelease": "Publier",

    "PleaseCreateChannel": "Créer une chaîne",
    "UploadTypeError": "Le format ne supporte pas",
    "UploadThumbnailError": "Veuillez montrer la vignette de la vidéo",
    "UploadTitleError": "S'il vous plaît entrez le titre",
    "SuccessfulRelease": "Publication avec succès",
    "FailedRelease": "Publication en échec",

    "__menu__": "",
    "Undo": "Annuler",
    "Redo": "Refaire",
    "Cut": "Écrêtage",
    "Copy": "Copier",
    "Paste": "Coller",
    "SelectAll": "Sélectionner tout"
}
