{
    "__common__": "",
    "Subscribe": "구독",
    "UnSubscribe": "구독취소",
    "VideoList": "재생목록",
    "Modify": "수정",
    "Video": "비디오",
    "Settings": "설정",
    "ChannelCategory": "범주",
    "ChannelTitle": "채널",
    "ChannelDescription": "채널설명",
    "Save": "저장",
    "Collection": "보관",
    "CommentContentPlaceholder": "공개 댓글 추가",
    "Comment": "댓글",
    "Reply": "답글",
    "Category1": "애완동물",
    "Category2": "영화 & 만화",
    "Category3": "공공 & 사회",
    "Category4": "교육",
    "Category5": "과학 & 기술",
    "Category6": "여행 & 레저 (leisure)",
    "Category7": "자동차",
    "Category8": "사람 & 블로그",
    "Category9": "스포츠",
    "Category10": "유머",
    "Category11": "뉴스 & 정치",
    "Category12": "음악",
    "Category13": "게임",
    "Category14": "연예",
    "Category15": "DIY & 생활",
    "Loading": "Cuckoo 로딩 중, 잠시만 기다려 주세요……",

    "__nav__": "",
    "PreviousPage": "이전",
    "NextPage": "다음",
    "Main": "홈",
    "Channels": "채널",
    "Refresh": "새로고침",
    "Code": "공유코드",
    "BtnCode": "검색",
    "Upload": "업로드",
    "My": "내 채널",

    "__footer__": "",
    "P2Pconnections": "P2P 연결",
    "SystemSettings": "설정",
    "P2PState": "사용 공간",
    "About": "Cuckoo 정보",

    "__my__": "",
    "ChannelTitleError": "당신의 채널이름을 입력하세요",
    "SuccessfullySetup": "설정 완료",
    "SetupFailed": "설정 실패",

    "__player__": "",
    "SuccessfulCollection": "성공적으로 수집",
    "AlreadyCollection": "즐겨찾기",
    "FailedCollection": "수집 실패",
    "SendCommentMsg": "귀하의 의견은 검토되고있다",
    "SendCommentMsgFailed": "30 초 이상의 간격으로 설명에 실패했습니다.",
    "SkipAd": "광고 건너뛰기",

    "__settings__": "",
    "FilePath": "파일",
    "FileSpace": "공간",
    "FileSpacePlaceholder": "공간 설정하기",
    "Lang": "언어",
    "BackUp": "백업",

    "FileSpaceFailedSave": "공간이 10GB 이상 필요합니다",
    "SuccessfullySaved": "저장 완료",
    "SuccessfullyBackUp": "백업 완료",
    "FailedBackUp": "백업 실패",

    "__upload__": "",
    "UploadCardTitle": "업로드할 파일을 선택하세요",
    "UploadCardText": "비디오 파일을 여기에 드래그하세요",
    "UploadThumbnail": "비디오 썸네일",
    "UploadMakeThumbnail": "스크린 썸네일",
    "UploadCategory": "카테고리",
    "UploadTitle": "제목",
    "UploadDescription": "설명",
    "UploadRelease": "배포",

    "PleaseCreateChannel": "채널을 만들어주세요",
    "UploadTypeError": "형식이 지원하지 않습니다.",
    "UploadThumbnailError": "썸네일은 필수입니다",
    "UploadTitleError": "제목은 필수입니다",
    "SuccessfulRelease": "성공적으로 배포되었습니다",
    "FailedRelease": "배포에 실패하였습니다",

    "__menu__": "",
    "Undo": "취소",
    "Redo": "되돌리기",
    "Cut": "잘라내기",
    "Copy": "복사하기",
    "Paste": "붙여넣기",
    "SelectAll": "모두 선택"
}
