{
    "__common__": "",
    "CuckooPort": "Cuckoo 포트",
    "GatewayPort": "인터넷 포트",
    "SwarmPort": "클러스터 포트",
    "Subscribe": "구독",
    "UnSubscribe": "구독취소",
    "VideoList": "재생목록",
    "Modify": "수정",
    "Video": "비디오",
    "Settings": "설정",
    "DeleteOrNot": "삭제를 확인?",
    "DeleteConfirm": "확인",
    "DeleteCancel": "취소하다",
    "ChannelCategory": "범주",
    "ChannelTitle": "채널",
    "ChannelDescription": "채널설명",
    "Save": "저장",
    "Collection": "보관",
    "CommentContentPlaceholder": "공개 댓글 추가",
    "CommentContentPlaceholderError": "사용자가 오프라인 상태 일 때 댓글 수 없습니다",
    "Comment": "댓글",
    "Reply": "답글",
    "Category1": "애완동물",
    "Category2": "영화 & 만화",
    "Category3": "공공 & 사회",
    "Category4": "교육",
    "Category5": "과학 & 기술",
    "Category6": "여행 & 레저 (leisure)",
    "Category7": "자동차",
    "Category8": "사람 & 블로그",
    "Category9": "스포츠",
    "Category10": "유머",
    "Category11": "뉴스 & 정치",
    "Category12": "음악",
    "Category13": "게임",
    "Category14": "연예",
    "Category15": "DIY & 생활",
    "Category16": "TV 쇼",
    "Category100": "성인 비디오",
    "SensitiveContent": "이 동영상에는 민감한 콘텐츠가있을 수 있습니다.",
    "View": "바라보다",
    "MySubscribe": "내 구독",
    "HotVideo": "인기있는 비디오",
    "RecommendVideo": "추천 비디오",
    "HotChannel": "인기 채널",
    "RecommendChannel": "추천 채널",
    "Loading": "Cuckoo 로드 중입니다. 잠시 기다려주세요.",
    "Quit": "로그오프",

    "__install__": "",
    "InstallTitle": "Cuckoo 설치",
    "InstallDirectory": "설치 디렉토리",
    "InstallSelect": "선택",
    "InstallLang": "언어",
    "Install": "설치",
    "InstallRecovery": "복구",

    "__nav__": "",
    "PreviousPage": "이전",
    "NextPage": "다음",
    "Main": "홈",
    "Channels": "채널",
    "Refresh": "새로고침",
    "Code": "공유코드",
    "BtnCode": "검색",
    "Upload": "업로드",
    "My": "내 채널",

    "__footer__": "",
    "P2Pconnections": "P2P 연결",
    "Preloading": "프리 로딩",
    "NoPreloadingTask": "프리로드 작업 없음",
    "SystemSettings": "설정",
    "P2PState": "사용 공간",
    "About": "Cuckoo 정보",

    "__my__": "",
    "ChannelTitleError": "당신의 채널이름을 입력하세요",
    "SuccessfullySetup": "설정 완료",
    "SetupFailed": "설정 실패",

    "__player__": "",
    "VideoCancel": "취소하다",
    "VideoReplay": "재연",
    "VideoPassword": "비디오 암호",
    "VideoDecrypt": "해독",

    "VideoCannotPlay": "이 비디오는 재생할 수 없습니다",
    "SuccessfulCollection": "성공적으로 수집",
    "AlreadyCollection": "즐겨찾기",
    "FailedCollection": "수집 실패",
    "SendCommentMsg": "귀하의 의견은 검토되고있다",
    "SendCommentMsgFailed": "30 초 간격 후에 의견을주십시오",
    "SkipAd": "광고 건너뛰기",
    "PasswordError": "잘못된 암호",

    "__settings__": "",
    "FilePath": "파일",
    "FileSpace": "공간",
    "FileSpacePlaceholder": "공간 설정하기",
    "Lang": "언어",
    "BackUp": "백업",

    "FileSpaceFailedSave": "공간이 10GB 이상 필요합니다",
    "SuccessfullySaved": "저장 완료",
    "SuccessfullyBackUp": "백업 완료",
    "FailedBackUp": "백업 실패",

    "__upload__": "",
    "UploadCardTitle": "업로드할 파일을 선택하세요",
    "UploadCardText": "비디오 파일을 여기에 드래그하세요",
    "UploadThumbnail": "비디오 썸네일",
    "UploadMakeThumbnail": "스크린 썸네일",
    "UploadCategory": "카테고리",
    "UploadTitle": "제목",
    "UploadDescription": "설명",
    "UploadPassword": "비밀번호 설정",
    "UploadRepassword": "암호 확인",
    "UploadRelease": "배포",

    "PleaseCreateChannel": "채널을 만들어주세요",
    "UploadTypeError": "이 형식은 지원되지 않습니다.",
    "UploadThumbnailError": "썸네일은 필수입니다",
    "UploadTitleError": "제목은 필수입니다",
    "UploadPasswordError": "두 개의 암호가 다릅니다.",
    "SuccessfulRelease": "성공적으로 배포되었습니다",
    "FailedRelease": "배포에 실패하였습니다",

    "__edit__": "",
    "EditPasswordPlaceholder": "암호가 비어 있으면 암호가 변경되지 않습니다.",
    "Edit": "수정",
    "EditTip": "사용 가능한 편집",
    "SuccessfulEdit": "성공적으로 편집",
    "FailedEdit": "실패 편집",

    "__menu__": "",
    "Undo": "취소",
    "Redo": "되돌리기",
    "Cut": "잘라내기",
    "Copy": "복사하기",
    "Paste": "붙여넣기",
    "SelectAll": "모두 선택"
}
