{
    "__common__": "",
    "CuckooPort": "Cuckoo Порт",
    "GatewayPort": "Порт шлюза",
    "SwarmPort": "Порт кластера",
    "Subscribe": "Подписаться",
    "UnSubscribe": "Отписаться",
    "VideoList": "Плэйлист",
    "Modify": "Изменить",
    "Video": "Видео",
    "Playlists": "Плейлисты",
    "Devices": "Приборы",
    "Settings": "Настройки",
    "DeleteOrNot": "Подтвердить удаление?",
    "DeleteConfirm": "подтвердить",
    "DeleteCancel": "отменен",
    "Add": "добавлять",
    "Edit": "редактировать",
    "ChannelCategory": "Категория",
    "ChannelTitle": "Канал",
    "ChannelDescription": "Описание Канала",
    "Save": "Сохранить",
    "SharingCode": "Получить Код",
    "Collection": "Коллекция",
    "CommentContentPlaceholder": "Оставьте комментарий",
    "CommentContentPlaceholderError": "Он не может быть прокомментирован, когда пользователь отключен",
    "Comment": "Оставить комментарий",
    "Reply": "ответить",
    "Category1": "Животные и Питомцы",
    "Category2": "Фильмы и Мультфильмы",
    "Category3": "Публичные и Социальные  Мероприятия",
    "Category4": "Образование",
    "Category5": "Наука и Техника",
    "Category6": "Туризм и Aктивный Отдых",
    "Category7": "Транспорт",
    "Category8": "Персональные блоги",
    "Category9": "Спорт",
    "Category10": "Юмор",
    "Category11": "Новости и Политика",
    "Category12": "Музыка",
    "Category13": "Игры",
    "Category14": "Развлечения",
    "Category15": "DIY и Быт",
    "Category16": "ТВ шоу",
    "Category100": "Видео взрослых",
    "SensitiveContent": "Это видео может содержать конфиденциальный контент",
    "View": "смотреть",
    "MySubscribe": "Моя подписка",
    "HotVideo": "Популярное видео",
    "RecommendVideo": "Рекомендуемое видео",
    "HotChannel": "Популярный канал",
    "RecommendChannel": "Рекомендуемый канал",
    "Loading": "Cuckoo загружается, пожалуйста, подождите некоторое время",
    "Quit": "закрывать",

    "__install__": "",
    "InstallTitle": "Установить Cuckoo",
    "InstallDirectory": "Каталог установки",
    "InstallSelect": "выбрать",
    "InstallLang": "Язык",
    "Install": "устанавливать",
    "InstallRecovery": "восстановление",

    "__nav__": "",
    "PreviousPage": "Предыдущая Страница",
    "NextPage": "Следуйщая Страница",
    "Main": "Главная",
    "Channels": "Канал",
    "Refresh": "Обновить",
    "Code": "Поиск или ввод кода совместного доступа",
    "BtnCode": "Просмотреть",
    "Upload": "Загрузка",
    "Download": "Скачать",
    "My": "Мой Канал",

    "__footer__": "",
    "P2Pconnections": "Моя Сеть",
    "Preloading": "Предзагрузка",
    "NoPreloadingTask": "Нет задачи  в  предварительной  загрузки",
    "SystemSettings": "Системные Настройки",
    "P2PState": "Место Использывано",
    "About": "Всё о Cuckoo",

    "__index__": "",
    "IndexMyEmpty": "Нет видео, для получения дополнительных видеороликов, пожалуйста проверьте ~HotVideo~ или ~RecommendVideo~",

    "__channels__": "",
    "ChannelsMyEmpty": "Нет подписанный канал, для большего количества каналов, пожалуйста, проверьте ~HotChannel~ или ~RecommendChannel~",

    "__my__": "",
    "MyVideoEmpty": "Если вы не разместили какое-либо видео, ~Upload~ видео, чтобы поделиться с семьей и друзьями",
    "MyPlaylistEmpty": "Нет плейлиста, нажмите кнопку ~+~, чтобы создать",
    "PlaylistTitle": "Название плейлиста",
    "PlaylistTitleError": "Повторить название плейлиста",
    "PlaylistThumbnail": "Эскиз плейлиста",
    "PlaylistDescription": "Описание плейлиста",
    "ClientManufacturer": "Производитель",
    "ClientBrand": "Марка",
    "ClientIP": "IP",
    "ClientUniqueID": "ID",
    "ChannelTitleError": "Введите название канала",
    "SuccessfullySetup": "Сохранить Настройки",
    "SetupFailed": "Ошибка",

    "__player__": "",
    "VideoCancel": "отменен",
    "VideoReplay": "переигрывать",
    "VideoPassword": "Видео-пароль",
    "VideoDecrypt": "Дешифрирование",
    "SetSubtitle": "Установить субтитры",
    "CurrentSubtitle": "Текущий субтитр",
    "SubtitleDelay": "Задержка субтитров",
    "SubtitleSize": "Размер субтитров",
    "SubtitlePosition": "Позиция субтитров",
    "SubtitleBackground": "Фон субтитров",
    "FloatOnTop": "Поплавок сверху",

    "VideoCannotPlay": "это видео не может быть воспроизведено",
    "SuccessfulCollection": "Успешно Добавленно",
    "AlreadyCollection": "Лучшее",
    "FailedCollection": "Не удалось добавить",
    "SendCommentMsg": "Bаши комментарии пересматриваются",
    "SendCommentMsgFailed": "прокомментировать после 30-секундного интервала",
    "SkipAd": "Пропустить Рекламу",
    "PasswordError": "Неверный пароль",

    "__settings__": "",
    "FilePath": "Файл",
    "DownloadPath": "Путь загрузки",
    "PathSelect": "выбрать",
    "FileSpace": "Место",
    "FileSpacePlaceholder": "Настройки Места",
    "Lang": "Язык",
    "BackUp": "Сохранить",
    "Theme": "тема",

    "FileSpaceFailedSave": "Для сохранения необходимо более чем 10GB",
    "SuccessfullySaved": "Успешно сохранено",
    "SuccessfullyBackUp": "Сохранено",
    "FailedBackUp": "Не сохранено",

    "__upload__": "",
    "UploadCardTitle": "Выбрать файл для загрузки",
    "UploadCardText": "Переместить видео-файл",
    "UploadThumbnail": "Миниатюра для видео",
    "UploadMakeThumbnail": "Миниатюра для экрана",
    "UploadCategory": "Категория",
    "UploadTitle": "Название",
    "UploadDescription": "Описание",
    "UploadSubtitles": "Установить субтитры",
    "UploadPassword": "Установить пароль",
    "UploadRepassword": "Подтвердить пароль",
    "UploadRelease": "Опубликовать",

    "PleaseCreateChannel": "Успешно Опубликовано",
    "UploadTypeError": "Этот формат не поддерживается",
    "UploadSubtitlesFile": "Файл субтитров",
    "UploadSubtitlesLabel": "Метка субтитров",
    "UploadThumbnailError": "Пожалуйста выберите миниатюру ",
    "UploadTitleError": "Пожалуйста выберите название",
    "UploadSubtitlesLabelError": "Метка субтитров не может быть пуста",
    "UploadPasswordError": "Два пароля различны",
    "SuccessfulRelease": "Успешно Опубликовано",
    "FailedRelease": "Ошибка Публикации",

    "__download__": "",
    "DownloadList": "Список загрузок",
    "DownloadPlaceholder": "Магнет-ссылка",
    "Downloaded": "загруженный",
    "DownloadRemaining": "остальной",
    "DownloadPaused": "Приостановлена",

    "__edit__": "",
    "EditPasswordPlaceholder": "Пароль не будет изменен, если он пуст",
    "EditTip": "Доступные редактирует",
    "SuccessfulEdit": "Успешное редактирование",
    "FailedEdit": "редактировать неудачно",

    "__search__": "",
    "SearchResults": "Результат поиска",

    "__menu__": "",
    "Undo": "Отменить",
    "Redo": "Редактировать",
    "Cut": "Удалить",
    "Copy": "Копировать",
    "Paste": "Вставить",
    "SelectAll": "Выбать все"
}
