{
    "__common__": "",
    "Subscribe": "Подписаться",
    "UnSubscribe": "Отписаться",
    "VideoList": "Плэйлист",
    "Modify": "Изменить",
    "Video": "Видео",
    "Settings": "Настройки",
    "ChannelCategory": "Категория",
    "ChannelTitle": "Канал",
    "ChannelDescription": "Описание Канала",
    "Save": "Сохранить",
    "Collection": "Коллекция",
    "CommentContentPlaceholder": "Оставьте комментарий",
    "Comment": "Оставить комментарий",
    "Reply": "ответить",
    "Category1": "Животные и Питомцы",
    "Category2": "Фильмы и Мультфильмы",
    "Category3": "Публичные и Социальные  Мероприятия",
    "Category4": "Образование",
    "Category5": "Наука и Техника",
    "Category6": "Туризм и Aктивный Отдых",
    "Category7": "Транспорт",
    "Category8": "Персональные блоги",
    "Category9": "Спорт",
    "Category10": "Юмор",
    "Category11": "Новости и Политика",
    "Category12": "Музыка",
    "Category13": "Игры",
    "Category14": "Развлечения",
    "Category15": "DIY и Быт",
    "Loading": "Cuckoo Подождите, идет загрузка……",

    "__nav__": "",
    "PreviousPage": "Предыдущая Страница",
    "NextPage": "Следуйщая Страница",
    "Main": "Главная",
    "Channels": "Канал",
    "Refresh": "Обновить",
    "Code": "Получить Код",
    "BtnCode": "Просмотреть",
    "Upload": "Загрузка",
    "My": "Мой Канал",

    "__footer__": "",
    "P2Pconnections": "Моя Сеть",
    "SystemSettings": "Системные Настройки",
    "P2PState": "Место Использывано",
    "About": "Всё о Cuckoo",

    "__my__": "",
    "ChannelTitleError": "Введите название канала",
    "SuccessfullySetup": "Сохранить Настройки",
    "SetupFailed": "Ошибка",

    "__player__": "",
    "SuccessfulCollection": "Успешно Добавленно",
    "AlreadyCollection": "Лучшее",
    "FailedCollection": "Не удалось добавить",
    "SendCommentMsg": "Bаши комментарии пересматриваются",
    "SendCommentMsgFailed": "Комментарий не выполнен с интервалом более 30 секунд",
    "SkipAd": "Пропустить Рекламу",

    "__settings__": "",
    "FilePath": "Файл",
    "FileSpace": "Место",
    "FileSpacePlaceholder": "Настройки Места",
    "Lang": "Язык",
    "BackUp": "Сохранить",

    "FileSpaceFailedSave": "Для сохранения необходимо более чем 10GB",
    "SuccessfullySaved": "Успешно сохранено",
    "SuccessfullyBackUp": "Сохранено",
    "FailedBackUp": "Не сохранено",

    "__upload__": "",
    "UploadCardTitle": "Выбрать файл для загрузки",
    "UploadCardText": "Переместить видео-файл",
    "UploadThumbnail": "Миниатюра для видео",
    "UploadMakeThumbnail": "Миниатюра для экрана",
    "UploadCategory": "Категория",
    "UploadTitle": "Название",
    "UploadDescription": "Описание",
    "UploadRelease": "Опубликовать",

    "PleaseCreateChannel": "Успешно Опубликовано",
    "UploadTypeError": "Формат не поддерживает",
    "UploadThumbnailError": "Пожалуйста выберите миниатюру ",
    "UploadTitleError": "Пожалуйста выберите название",
    "SuccessfulRelease": "Успешно Опубликовано",
    "FailedRelease": "Ошибка Публикации",

    "__menu__": "",
    "Undo": "Отменить",
    "Redo": "Редактировать",
    "Cut": "Удалить",
    "Copy": "Копировать",
    "Paste": "Вставить",
    "SelectAll": "Выбать все"
}
