{
    "__common__": "",
    "Subscribe": "订阅",
    "UnSubscribe": "取消订阅",
    "VideoList": "视频列表",
    "Modify": "修改",
    "Video": "视频",
    "Settings": "设置",
    "ChannelCategory": "频道类型",
    "ChannelTitle": "频道名称",
    "ChannelDescription": "频道描述",
    "Save": "保存",
    "Collection": "收藏",
    "CommentContentPlaceholder": "发表公开评论",
    "Comment": "提交评论",
    "Reply": "回复",
    "Category1": "宠物和动物",
    "Category2": "电影和动画",
    "Category3": "公益与社会活动",
    "Category4": "教育",
    "Category5": "科学和技术",
    "Category6": "旅游和活动",
    "Category7": "汽车",
    "Category8": "人物和博客",
    "Category9": "体育",
    "Category10": "喜剧",
    "Category11": "新闻和政治",
    "Category12": "音乐",
    "Category13": "游戏",
    "Category14": "娱乐",
    "Category15": "DIY 和生活百科",
    "Category100": "成人视频",
    "SensitiveContent": "此媒体可能含有敏感内容",
    "View": "查看",
    "Loading": "Cuckoo正在初始化，请耐心等待……",

    "__nav__": "",
    "PreviousPage": "上一页",
    "NextPage": "下一页",
    "Main": "首页",
    "Channels": "频道",
    "Refresh": "刷新",
    "Code": "分享码",
    "BtnCode": "查看",
    "Upload": "上传",
    "My": "我的",

    "__footer__": "",
    "P2Pconnections": "节点数",
    "SystemSettings": "系统设置",
    "P2PState": "空间已使用",
    "About": "关于",

    "__my__": "",
    "ChannelTitleError": "频道名称不能为空",
    "SuccessfullySetup": "设置成功",
    "SetupFailed": "设置失败",

    "__player__": "",
    "VideoCancel": "取消",
    "VideoReplay": "重播",

    "SuccessfulCollection": "收藏成功",
    "AlreadyCollection": "已经收藏",
    "FailedCollection": "收藏失败",
    "SendCommentMsg": "您的评论正在审核中",
    "SendCommentMsgFailed": "评论失败，间隔需大于30秒",
    "SkipAd": "跳过广告",

    "__settings__": "",
    "FilePath": "文件路径",
    "FileSpace": "文件空间",
    "FileSpacePlaceholder": "设置空间",
    "Lang": "选择语言",
    "BackUp": "备份",

    "FileSpaceFailedSave": "文件空间必须大于10GB",
    "SuccessfullySaved": "保存成功",
    "SuccessfullyBackUp": "备份成功",
    "FailedBackUp": "备份失败",

    "__upload__": "",
    "UploadCardTitle": "选择要上传的文件",
    "UploadCardText": "或将视频文件拖放到此处",
    "UploadThumbnail": "视频缩略图",
    "UploadMakeThumbnail": "截为缩略图",
    "UploadCategory": "类型",
    "UploadTitle": "标题",
    "UploadDescription": "文件描述",
    "UploadRelease": "发布",

    "PleaseCreateChannel": "请创建频道",
    "UploadTypeError": "格式不支持",
    "UploadThumbnailError": "视频缩略图不能为空",
    "UploadTitleError": "标题不能为空",
    "SuccessfulRelease": "发布成功",
    "FailedRelease": "发布失败",

    "__menu__": "",
    "Undo": "撤销",
    "Redo": "重做",
    "Cut": "剪切",
    "Copy": "复制",
    "Paste": "粘贴",
    "SelectAll": "全选"
}
