{
    "__common__": "",
    "CuckooPort": "Cuckoo端口",
    "GatewayPort": "网关端口",
    "SwarmPort": "集群端口",
    "Subscribe": "订阅",
    "UnSubscribe": "取消订阅",
    "VideoList": "视频列表",
    "Modify": "修改",
    "Video": "视频",
    "Playlists": "播放列表",
    "Settings": "设置",
    "DeleteOrNot": "确认删除?",
    "DeleteConfirm": "确认",
    "DeleteCancel": "取消",
    "Add": "添加",
    "Edit": "编辑",
    "ChannelCategory": "频道类型",
    "ChannelTitle": "频道名称",
    "ChannelDescription": "频道描述",
    "Save": "保存",
    "SharingCode": "分享码",
    "Collection": "收藏",
    "CommentContentPlaceholder": "发表公开评论",
    "CommentContentPlaceholderError": "对方不在线无法进行评论",
    "Comment": "提交评论",
    "Reply": "回复",
    "Category1": "宠物和动物",
    "Category2": "电影和动画",
    "Category3": "公益与社会活动",
    "Category4": "教育",
    "Category5": "科学和技术",
    "Category6": "旅游和活动",
    "Category7": "汽车",
    "Category8": "人物和博客",
    "Category9": "体育",
    "Category10": "喜剧",
    "Category11": "新闻和政治",
    "Category12": "音乐",
    "Category13": "游戏",
    "Category14": "娱乐",
    "Category15": "DIY 和生活百科",
    "Category16": "电视节目",
    "Category100": "成人视频",
    "SensitiveContent": "此媒体可能含有敏感内容",
    "View": "查看",
    "MySubscribe": "我的订阅",
    "HotVideo": "热门视频",
    "RecommendVideo": "推荐视频",
    "HotChannel": "热门频道",
    "RecommendChannel": "推荐频道",
    "Loading": "Cuckoo正在初始化，请耐心等待……",
    "Quit": "退出",

    "__install__": "",
    "InstallTitle": "安装 Cuckoo",
    "InstallDirectory": "安装目录",
    "InstallSelect": "选择",
    "InstallLang": "选择语言",
    "Install": "安装",
    "InstallRecovery": "恢复",

    "__nav__": "",
    "PreviousPage": "上一页",
    "NextPage": "下一页",
    "Main": "首页",
    "Channels": "频道",
    "Refresh": "刷新",
    "Code": "搜索或输入分享码",
    "BtnCode": "查看",
    "Upload": "上传",
    "My": "我的",

    "__footer__": "",
    "P2Pconnections": "节点数",
    "Preloading": "预加载",
    "NoPreloadingTask": "没有任务正在加载",
    "SystemSettings": "系统设置",
    "P2PState": "空间已使用",
    "About": "关于",

    "__index__": "",
    "IndexMyEmpty": "没有视频，可以查看~HotVideo~或者~RecommendVideo~获取更多",

    "__channels__": "",
    "ChannelsMyEmpty": "没有订阅频道，可以查看~HotChannel~或者~RecommendChannel~获取更多",

    "__my__": "",
    "MyVideoEmpty": "如果您还没有发布视频，请~Upload~一个视频与您的家人和朋友分享",
    "MyPlaylistEmpty": "没有播放列表，请点击~+~按钮创建",
    "PlaylistTitle": "播放列表标题",
    "PlaylistTitleError": "播放列表标题重复",
    "PlaylistThumbnail": "播放列表缩略图",
    "PlaylistDescription": "播放列表描述",
    "ChannelTitleError": "频道名称不能为空",
    "SuccessfullySetup": "设置成功",
    "SetupFailed": "设置失败",

    "__player__": "",
    "VideoCancel": "取消",
    "VideoReplay": "重播",
    "VideoPassword": "视频密码",
    "VideoDecrypt": "解密",
    "SetSubtitle": "设置字幕",
    "CurrentSubtitle": "当前字幕",
    "SubtitleDelay": "字幕延迟",
    "SubtitleSize": "字幕大小",
    "SubtitlePosition": "字幕位置",
    "SubtitleBackground": "字幕背景",

    "VideoCannotPlay": "视频无法播放",
    "SuccessfulCollection": "收藏成功",
    "AlreadyCollection": "已经收藏",
    "FailedCollection": "收藏失败",
    "SendCommentMsg": "您的评论正在审核中",
    "SendCommentMsgFailed": "评论失败，间隔需大于30秒",
    "SkipAd": "跳过广告",
    "PasswordError": "密码错误",

    "__settings__": "",
    "FilePath": "文件路径",
    "FileSpace": "文件空间",
    "FileSpacePlaceholder": "设置空间",
    "Lang": "选择语言",
    "BackUp": "备份",

    "FileSpaceFailedSave": "文件空间必须大于10GB",
    "SuccessfullySaved": "保存成功",
    "SuccessfullyBackUp": "备份成功",
    "FailedBackUp": "备份失败",

    "__upload__": "",
    "UploadCardTitle": "选择要上传的文件",
    "UploadCardText": "或将视频文件拖放到此处",
    "UploadThumbnail": "视频缩略图",
    "UploadMakeThumbnail": "截为缩略图",
    "UploadCategory": "类型",
    "UploadTitle": "标题",
    "UploadDescription": "文件描述",
    "UploadPassword": "设置密码",
    "UploadRepassword": "确认密码",
    "UploadRelease": "发布",

    "PleaseCreateChannel": "请创建频道",
    "UploadTypeError": "格式不支持",
    "UploadThumbnailError": "视频缩略图不能为空",
    "UploadTitleError": "标题不能为空",
    "UploadPasswordError": "两次密码不同",
    "SuccessfulRelease": "发布成功",
    "FailedRelease": "发布失败",

    "__edit__": "",
    "EditPasswordPlaceholder": "为空则不修改密码",
    "EditTip": "可执行的编辑",
    "SuccessfulEdit": "编辑成功",
    "FailedEdit": "编辑失败",

    "__search__": "",
    "SearchResults": "搜索结果",

    "__menu__": "",
    "Undo": "撤销",
    "Redo": "重做",
    "Cut": "剪切",
    "Copy": "复制",
    "Paste": "粘贴",
    "SelectAll": "全选"
}
